# Generated by Django 3.2.7 on 2021-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('career', models.IntegerField()),
                ('ward', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('duty', models.CharField(blank=True, max_length=31)),
            ],
        ),
    ]
