# Generated by Django 3.2.7 on 2021-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211025_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.JSONField(blank=True),
        ),
    ]
