# Generated by Django 3.2.7 on 2021-11-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211101_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
